import type { InterviewTypeInfo } from '@/types/interviewType';

export const SYSTEM_INTERVIEW_TYPES: InterviewTypeInfo[] = [
  {
    id: 'sys_it_technical',
    slug: 'technical',
    name: 'Technical',
    description: 'Assess coding, system design, and engineering depth.',
    interview_type: 'technical',
    scope: 'system',
    default_duration_minutes: 45,
    default_level: 'mid',
    status: 'active',
    tenant_id: null,
  },
  {
    id: 'sys_it_behavioral',
    slug: 'behavioral',
    name: 'Behavioral',
    description: 'Past behavior, ownership, and collaboration patterns.',
    interview_type: 'behavioral',
    scope: 'system',
    default_duration_minutes: 30,
    default_level: 'mid',
    status: 'active',
    tenant_id: null,
  },
  {
    id: 'sys_it_hr',
    slug: 'hr',
    name: 'HR',
    description: 'Background, motivation, compensation, and logistics.',
    interview_type: 'hr',
    scope: 'system',
    default_duration_minutes: 20,
    default_level: 'entry',
    status: 'active',
    tenant_id: null,
  },
  {
    id: 'sys_it_communication',
    slug: 'communication',
    name: 'Communication',
    description: 'Clarity, articulation, and structured thinking.',
    interview_type: 'communication',
    scope: 'system',
    default_duration_minutes: 25,
    default_level: 'mid',
    status: 'active',
    tenant_id: null,
  },
  {
    id: 'sys_it_managerial',
    slug: 'managerial',
    name: 'Managerial',
    description: 'Leadership, people management, and strategic thinking.',
    interview_type: 'managerial',
    scope: 'system',
    default_duration_minutes: 40,
    default_level: 'senior',
    status: 'active',
    tenant_id: null,
  },
  {
    id: 'sys_it_cultural_fit',
    slug: 'cultural_fit',
    name: 'Cultural Fit',
    description: 'Values alignment and team culture compatibility.',
    interview_type: 'cultural_fit',
    scope: 'system',
    default_duration_minutes: 30,
    default_level: 'mid',
    status: 'active',
    tenant_id: null,
  },
  {
    id: 'sys_it_screening',
    slug: 'screening',
    name: 'Screening',
    description: 'Initial filter for must-have skills and experience.',
    interview_type: 'screening',
    scope: 'system',
    default_duration_minutes: 15,
    default_level: 'entry',
    status: 'active',
    tenant_id: null,
  },
];

export const INITIAL_TENANT_INTERVIEW_TYPES: InterviewTypeInfo[] = [
  {
    id: 'it_tenant_001',
    slug: 'domain_expert',
    name: 'Domain Expert',
    description: 'Deep domain knowledge assessment for specialized roles.',
    interview_type: 'domain_expert',
    scope: 'tenant',
    default_duration_minutes: 40,
    default_level: 'senior',
    status: 'active',
    tenant_id: 'tenant_abc',
    created_at: '2026-07-20T09:00:00Z',
    updated_at: '2026-07-22T14:30:00Z',
  },
  {
    id: 'it_tenant_002',
    slug: 'leadership',
    name: 'Leadership Assessment',
    description: 'Evaluate leadership style, vision, and team building.',
    interview_type: 'leadership',
    scope: 'tenant',
    default_duration_minutes: 50,
    default_level: 'senior',
    status: 'active',
    tenant_id: 'tenant_abc',
    created_at: '2026-07-25T10:00:00Z',
    updated_at: '2026-07-25T10:00:00Z',
  },
];
